[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate",
  "pnpm install --frozen-lockfile || pnpm install"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node build/index.js"

[variables]
NODE_ENV = "production"
